spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/countries_dev
    username: postgres
    password: p.postgres
  jpa:
    #database-platform: org.hibernate.dialect.PostgresSQLDialect    //bunu açınca hata veriyor çalışmıyor çünkü zaten sadece postgresql var bizde
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false





#branchi olusturduktan sonra meslea db_connection diye bir branc olusturmustuk bununla isimiz bitti databaseyi bagladik
#artik bu branci main branchine merge edip silmememiz gerekiyor
# git add.
# git commit -m "sss"
# git branch  //kontrol için
# git log //neler değişmiş
# git checkout main  //maine geç geçtiğinde yaptığın değişiklikler daha maine aktarılmadı
# git merge db_connection

# git branch -D db_connection //artık branchi silebiliriz silme komutu sadece main kaldı.

#bu dal işlemlerini: iş takibini kolaylaştırmak için, belli iş paketlerini sadece belirli branchlerde yapabilmek için
#proje takibi ve yönetilmesini kolaylastiriyor.